apiVersion: apps/v1
kind: Deployment
metadata:
  name: lgtm-frontend
  namespace: lgtm
  labels:
    app: lgtm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm-frontend
  template:
    metadata:
      labels:
        app: lgtm-frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: lgtm/frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
